# https://docs.docker.com/compose/yml/

bitcoin-unlimited:
  container_name: bitcoin-unlimited
  hostname: bitcoin-unlimited
  image: mgcrea/bitcoin-unlimited:1
  environment:
    - IMAGE_USER=www-data
    - IMAGE_GROUP=www-data
    - UID=33
    - GID=33
  ports:
    - "8333:8333"
  volumes:
    - ./data:/var/bitcoin
  restart: always